sudo: required
language: node_js
node_js:
  - "0.10"
  - "4"
  
before_install:
  - "curl -L http://git.io/ejPSng | /bin/sh"
  -  "cd example-package; meteor add percolate:synced-cron@=1.3.0"

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
